@startuml
package "tfm-back-front-end" <<Folder>> {

    package "tfm-back-front-end.TFMGoSki" <<Folder>> {   
        package "tfm-back-front-end.TFMGoSki.github" <<Folder>> {
            package "tfm-back-front-end.TFMGoSki.github.workflows" <<Folder>> {
            }
        }
        package "tfm-back-front-end.TFMGoSki.TFMGoSki" <<Folder>> {
            package "tfm-back-front-end.TFMGoSki.TFMGoSki.Controllers" <<Folder>> {
            }
            package "tfm-back-front-end.TFMGoSki.TFMGoSki.Data" <<Folder>> {
            }
            package "tfm-back-front-end.TFMGoSki.TFMGoSki.Migrations" <<Folder>> {
            }
            package "tfm-back-front-end.TFMGoSki.TFMGoSki.Models" <<Folder>> {
            }
            package "tfm-back-front-end.TFMGoSki.TFMGoSki.Views" <<Folder>> {
            }
        }
        package "tfm-back-front-end.TFMGoSki.database" <<Folder>> {
        }
    }
}
@enduml